package org.chatapp.component;

import org.chatapp.model.ModelUserAccount;

import javax.swing.*;
import java.awt.*;

public class Chat_Title extends JPanel {
    private ModelUserAccount modelUserAccount;

    public ModelUserAccount getModelUserAccount() {
        return modelUserAccount;
    }

    public void setModelUserAccount(ModelUserAccount modelUserAccount) {
        this.modelUserAccount = modelUserAccount;
        lbName.setText(modelUserAccount.getUsername());
        if (modelUserAccount.isStatus()) {
            statusActive();
        } else {
            setStatusText("Offline");
        }
    }

    public Chat_Title() {
        initComponents();
    }
    public void updateUser(ModelUserAccount modelUserAccount) {
        if (this.modelUserAccount == modelUserAccount) {
            lbName.setText(modelUserAccount.getUsername());
            if(modelUserAccount.isStatus()) {
                statusActive();
            }else {
                setStatusText("Offline");
            }
        }
    }

    public void setUserName(String userName) {
        lbName.setText(userName);
    }

    private void statusActive() {
        lbStatus.setText("Active now");
        lbStatus.setForeground(new Color(40, 147, 59));
    }

    private void setStatusText(String text) {
        lbStatus.setText(text);
        lbStatus.setForeground(new Color(160, 160, 160));
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layer = new JLayeredPane();
        lbName = new JLabel();
        lbStatus = new JLabel();

        setBackground(new Color(242, 242, 242));

        layer.setLayout(new GridLayout(0, 1));

        lbName.setFont(new Font("sansserif", 1, 14)); // NOI18N
        lbName.setForeground(new Color(66, 66, 66));
        lbName.setText("Name");
        layer.add(lbName);

        lbStatus.setForeground(new Color(40, 147, 59));
        lbStatus.setText("Active now");
        layer.add(lbStatus);

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(layer, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(406, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(layer, GroupLayout.PREFERRED_SIZE, 34, Short.MAX_VALUE)
                                .addGap(3, 3, 3))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLayeredPane layer;
    private JLabel lbName;
    private JLabel lbStatus;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    }
    // End of variables declaration//GEN-END:variables
}
